### ISSUE TITLE
Fix typos of the README and CONTRIBUTING markdown files

### ISSUE THREAD

**Issue by jinhale** [edhowland/viper#2]
I'm going for consistency besides fixing typos. So if hyphens are used, then colons, then hyphens again, and all are used for the same delimiting purpose I will replace the odd delimiter with the more common delimiter for the given context. 

I would like to remove unneeded white space and format rows of text to be no wider than about 72 character columns wide.

**Comment by edhowland** [comment]
I merged the PR that fixed this issue.
